import google.generativeai as genai
from PIL import Image, ImageDraw

import io
import os
import json
from dotenv import load_dotenv
from google.generativeai import types

from utils.ai_prompts import create_prompt_for_object_detection

"""
this script will be relevant later on for a browser agent to click on things etc.
"""

# Load API key from .env file
load_dotenv()
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

def get_object_center(image_path, prompt, debug=False):
    """
    Finds the center coordinates of a bounding box generated by Gemini for a given object in an image.

    Args:
        image_path: The path to the image file.
        prompt: The search query to find the object (e.g., "Find the red apple").

    Returns:
        A tuple (center_x, center_y) representing the center coordinates of the bounding box,
        or None if no bounding box is found or if there's an error.
    """

    model_name = "gemini-2.0-flash-thinking-exp"  # You can change the model if needed

    bounding_box_system_instructions = """
        prompt = create_prompt_for_object_detection(image_path)
          """

    

    # Load and resize image
    try:
        img = Image.open(image_path)
    except FileNotFoundError:
        print(f"Error: Image not found at {image_path}")
        return None
    except Exception as e:
        print(f"Error processing image: {e}")
        return None

    # Run model to find bounding boxes
    try:
        model = genai.GenerativeModel(model_name)
        response = model.generate_content(
            [create_prompt_for_object_detection(image_path), img],
            generation_config=genai.types.GenerationConfig(
                candidate_count=1,
                max_output_tokens=2000,
                temperature=0.5,  # Adjust temperature if needed
            ),
        )
    except Exception as e:
        print(f"Error with Gemini API: {e}")
        return None

    # Parse JSON output (assuming Gemini returns a valid JSON array)
    try:
        print(response.text)
        bounding_boxes = parse_json(response.text)
        bounding_boxes = json.loads(bounding_boxes)

        if not bounding_boxes:
            print("No bounding box found for the given prompt.")
            return None

        # Assuming only one bounding box
        bounding_box = bounding_boxes[0]["box_2d"]
    except (json.JSONDecodeError, IndexError, KeyError, TypeError):
        print("Error parsing bounding box information from Gemini's response.")
        return None

    # Convert normalized coordinates to absolute coordinates
    width, height = img.size
    y1, x1, y2, x2 = bounding_box
    
    abs_y1 = int(y1 / 1000 * height)
    abs_x1 = int(x1 / 1000 * width)
    abs_y2 = int(y2 / 1000 * height)
    abs_x2 = int(x2 / 1000 * width)
    
    if abs_x1 > abs_x2:
      abs_x1, abs_x2 = abs_x2, abs_x1

    if abs_y1 > abs_y2:
      abs_y1, abs_y2 = abs_y2, abs_y1
      
    debug = True
    if debug == True:
        draw = ImageDraw.Draw(img)
        draw.rectangle([(abs_x1, abs_y1), (abs_x2, abs_y2)], outline="red", width=5)
        img.show()
    
    # Calculate center coordinates
    center_x = (abs_x1 + abs_x2) // 2
    center_y = (abs_y1 + abs_y2) // 2

    return center_x, center_y

def parse_json(json_output):
    """Helper function to extract JSON from Gemini's response (handles markdown fencing)."""
    lines = json_output.splitlines()
    for i, line in enumerate(lines):
        if line == "```json":
            json_output = "\n".join(lines[i + 1:])
            json_output = json_output.split("```")[0]
            break
    return json_output

# Example usage (assuming you have an image 'Socks.jpg' and a .env file):
if __name__ == "__main__":
    
    # Example usage (assuming you have an image 'Socks.jpg'):
    image_path = "google_screen_shot.png"  # Replace with your image path
    prompt = "Detect the 2d bounding boxes of the first link/result in this google search that is not an ad and from youtube. if no youtube link then a reddit link. if also no reddit then any site. We want the bounding boxes to be specifically where we can click to open the link, not the whole object. Just where we are supposed to click."  # Replace with your search query

    center_coordinates = get_object_center(image_path, prompt)

    if center_coordinates:
        center_x, center_y = center_coordinates
        print(f"Center coordinates of the object: ({center_x}, {center_y})")

        im = Image.open(image_path)
        draw = ImageDraw.Draw(im)

        # Draw a small circle to mark the center
        radius = 40
        draw.ellipse([(center_x - radius, center_y - radius), (center_x + radius, center_y + radius)], fill="red")

        # Display the image
        im.show()
    else:
        print("Could not find the object or there was an error.")

